Patterns = {
 "Default": "",

 #https://ruwix.com/the-rubiks-cube/rubiks-cube-patterns-algorithms/
 "The Superflip": "U R2 F B R B2 R U2 L B2 R U' D' R2 F R' L B2 U2 F2",
 "The easy checkerboard": "U2 D2 F2 B2 L2 R2",
 "Speedsolving.com logo": "R' L' U2 F2 D2 F2 R L B2 U2 B2 U2",
 "All flags & crests": "B2 U' B2 L2 U B2 U R2 B2 U' L' R' B D U' L2 F2 R'",
 "Wire": "R L F B R L F B R L F B R2 B2 L2 R2 B2 L2",
 "Checkerboard in the cube": "B D F' B' D L2 U L U' B D' R B R D' R L' F U2 D",
 "( ! ) (ˆ⌣ˆԅ)": "U' F2 R' L' U' B R2 D B U' R2 L B2 D' B2 U F2 B2 U' L2 B2 L2",
 "Minority cross": "L2 D' B2 L2 B2 D' F2 D U' B2 L B2 F' L B' F U' F' U L2",
 "Perpendicular lines": "R2 U2 L2 R2 U2 L2 M2",
 "Flipped tips": "U B D' F2 D B' U' R2 D F2 D' R2 D F2 D' R2",
 "Plus minus": "U2 R2 L2 U2 R2 L2",
 "Tablecloth": "R L U2 F' U2 D2 R2 L2 F' D2 F2 D R2 L2 F2 B2 D B2 L2",
 "Deckerboard": "U D R L' F' B U D' R2 U R2 L2 D2 F2 B2 D",
 "Spiral pattern": "L' B' D U R U' R' D2 R2 D L D' L' R' F U",
 "Fruit bowl": "B2 L2 F2 R2 F2 R2 D U B2 U2 B' F' L' R' D' U'",
 "Flower": "R2 D2 R2 U2 R2 F2 U2 D2 F2 U2",
 "Vertical stripes": "F U F R L2 B D' R D2 L D' B R2 L F U F",
 "Gift box": "U B2 R2 B2 L2 F2 R2 D' F2 L2 B F' L F2 D U' R2 F' L' R'",
 "Opposite corners": "R L U2 F2 D2 F2 R L F2 D2 B2 D2",
 "Cross": "R2 L' D F2 R' D' R' L U' D R D B2 R' U D2",
 "4 crosses": "F2 B2 R F2 B2 R F2 B2 R F2 B2 R F2 B2 R F2 B2 R",
 "Union Jack (Крест)": "U F B' L2 U2 L2 F' B U2 L2 U",
 "Cube in the cube": "F L F U' R U F2 L2 U' L' B D' B' L2 U",
 "Cube in a cube in a cube": "U' L' U' F' R2 B' R F U B2 U B' L U' F U R F'",
 "Anaconda": "L U B' U' R L' B R' F B' D R D' F'",
 "Python": "F2 R' B' U R' L F' L F' B D' R B L2",
 "Black mamba": "R D L F' R L' D R' U D' B U' R' D'",
 "Green mamba": "R D R F R' F' B D R' U' B' U D2",
 "Tangled": "F B U D F B U D F B U D F2 B2",
 "Four spots": "F2 B2 U D' R2 L2 U D'",
 "Six spots": "U D' R L' F B' U D'",
 "Twister": "F R' U L F' L' F U' R U L' U' L F'",
 "Kilt (Scottish skirt)": "U' R2 L2 F2 B2 U' R L F B' U F2 D2 R2 L2 F2 U2 F2 U' F2",
 "Tetris (Yan Ying)": "L R F B U' D' L' R'",
 "Don't cross line": "F2 L2 R2 B2 E2",
 "Hi": "M2 U2 M2 U2",
 "Hi all around": "U2 R2 F2 U2 D2 F2 L2 U2",
 "Hi again": "U2 D2 L2 U2 D2 R2 F2 B2 L2 F2 B2 R2 U2 D2 F2 U2 D2 B2",
 "Displaced Motif": "L2 B2 D' B2 D L2 U R2 D R2 B U R' F2 R U' B' U'",
 "Are you high?": "L R' U2 D2 L' R U2 D2 R2 L2",
 "C U around": "U' B2 U L2 D L2 R2 D' B' R D' L R' B2 U2 F' L' U'",
 "Order in chaos": "B L2 B' U2 B F2 U L U B U' R U' B F U' R D R B' U'",
 "Opposite pillars": "R2 F2 L2 R2 F2 L2",
 "Viaduct": "R2 U2 L2 D B2 L2 B2 R2 D' U L' D F' U' R2 F' U B2 U2 R'",
 "Solved in scrambled": "U2 L' U2 L' U2 F2 D L F' L F R2 D' B2 D' L2 D' L2 F2 R2",
 "Hi Ohio": "U2 F2 L2 R2 F2 U2",
 "Staircase": "L2 F2 D' L2 B2 D' U' R2 B2 U' L' B2 L D L B' D L' U",
 "Wrapped 2x2": "D' B2 F2 L2 U' F2 R2 D F2 U2 L' B R' U' L' F D' F L D2",
 "Antipodal chaos": "U2 L2 U2 L2 U2 F2 R2 F2 U2 F2",
 "Flower field": "M S M' S' R2 L2 U2 D2 F2 B2",
 "C spirals": "B' F' L2 D2 B' F U2 R2 F2",
 "Worms": "U' F2 L2 U D2 F2 B2 U F2 L2 D",
 "Glider": "D2 R2 F2 R2 U2 B2 D2 F2 L2 U2 R2 U2",
 "Quote": "U2 F2 D2 B2 R2 U2 B2 R2 U2 R2",
 "Matching pictures": "R' D2 R L D2 L'",
 "Loose strap": "F2 U2 B2 U2 F2 U2",
 "Doubler": "R L U2 R L' D2 R2 F2 U2 F2 U2 L2 F2 U2 L2",
 "3T": "B U2 L2 F2 R2 F D2 F2 R2 F' R2 U2",
 "4T": "F2 D2 F' L2 D2 U2 R2 B' U2 F2",
 "6T": "F2 R2 U2 F' B D2 L2 F B",
 "ZZ-Line": "R L U2 R L' U2 F2 R2 U2 F2 D2 B2 L2 U2 L2",
 "Checker zigzag": "R2 L2 F2 B2 U F2 B2 U2 F2 B2 U",
 "Exchanged duck feet": "U F R2 F' D' R U B2 U2 F' R2 F D B2 R B'",
 "Stripe dot solved": "D U B2 F2 D' U'",
 "Picnic": "D2 R2 L2 F2 B2",
 "Percent sign %": "R L U2 R L' U2 F2 L2 U2 F2 U2 F2 R2 U2 R2",
 "Mirror": "U D F2 B2 U' D' R2 L2 B2",
 "Plus minus check": "U D R2 L2 U D R2 L2",
 "Facing checkerboards": "U2 F2 U2 F2 B2 U2 F2 D2",
 "4 plus 2 dots": "F U2 D2 R L U' D F B R U2 R2 U2 F2 L2 U2 F2 L2 B2",
 "Rockets": "U R2 F2 R2 U' D F2 R2 F2 D",
 "Slash (Zig Zag. Слэш, полоски. Зигзаг)": "R L F B R L F B R L F B",
 "The pillars": "L2 R2 B2 F2",
 "Twisted duck feet": "F R' B R U F' L' F' U2 L' U' D2 B D' F B' U2",
 "Ron's cube in a cube": "F D' F' R D F' R' D R D L' F L D R' F D'",
 "Headlights": "U2 F2 U2 D2 B2 D2",
 "Crossing snake": "R L U2 R L' U2 F2 R2 D2 B2 D2 B2 L2 D2 R2",
 "Cage": "L U F2 R L' U2 B' U D B2 L F B' R' L F' R",
 "Four crosses": "U2 R2 L2 F2 B2 D2 L2 R2 F2 B2",
 "Pyraminx": "D L' U R' B' R B U2 D B D' B' L U D'",
 "Edge triangle": "U B2 U' F' U' D L' D2 L U D' F D' L2 B2 D'",
 "Twisted rings": "F D F' D2 L' B' U L D R U L' F' U L U2",
 "Exchanged rings": "B' U' B' L' D B U D2 B U L D' L' U' L2 D",
 "Twisted chicken feet": "F L' D F' U' B U F U' F R' F2 L U' R' D2",
 "Exchanged chicken feet": "F L' D' B' L F U F' D' F L2 B' R' U L2 D' F",
 "Twin Peaks": "U L2 B2 R2 U R2 D' U L F' U L' D B' U L B' L R' U'",
 "Corner pyramid": "U' D B R' F R B' L' F' B L F R' B' R F' U' D",
 "Twisted peaks": "F B' U F U F U L B L2 B' U F' L U L' B",
 "Exchanged peaks": "F U2 L F L' B L U B' R' L' U R' D' F' B R2",
 "Megatron": "U L D R' F D2 R2 F2 R' F D2 B L2 U2 D' R2 U R2 B2 L2",
 "Six-two-one": "U B2 D2 L B' L' U' L' B D2 B2",
 "Yin Yang": "R L B F R L U' D' F' B' U D",
 "Henry's snake": "R2 F2 U' D' B2 L2 F2 L2 U D R2 F2",
 "Snake eyes": "R2 U2 R2 U2 R2 U2",
 "Glitch": "F' L' B' R' U' R B L F U",
 "Weirdo": "R' F' U F2 U' F R' F2 D2 F2 D2 F2 D F2 R2 U2",
 "Twisted corners": "F U D R2 F2 U' B U B U R2 B' U L2 U B2 U2 F2 L2 U'",
 "Quick maths 1+1": "R L F2 U2 R' L' F2 U2 R2 F2 U R2 L2 F2 B2 D'",

 #https://kubikus.top/uzory-na-kubike-rubika/
 "Крест Пламмера (вариант 1)": "B F2 D' R2 F D B' F D' U F' D' L2 F D2 U'",
 "Крест Пламмера (вариант 2)": "z' U2 M2 U M2 U2 S2 D' S2 z U2 M2 U M2 U2 S2 D' S2",
 "Шесть букв Н": "D2 M' S2 M U2",

 # https://shveda.ru/igry-s-kubikom-rubika-6-prostyh-uzorov/
 "Six spots (Точки. Шесть точек. Замена центров)": "S' M' S M",
 "The easy checkerboard (Простая шахматная доска. Ослиный мостик) (Вариант 1)": "M2 E2 S2",
 "The easy checkerboard (Простая шахматная доска. Ослиный мостик) (Вариант 2)": "S2 E2 M2",
 "Flower field (Мостик с точками. Цветочное поле. Ослиный мостик с точками)": "M2 E2 S2 S' M' S M",
 "Two letters H (Две буквы Н)": "U2 M2 U2 M2",
 "Four letter Z (Четыре буквы Z)": "R L F B R L F B R L F B U2 D2",

 # https://dedfoma.ru/kubikrubika/uzory-na-kubike-rubika.htm
 "Глобус Д. Максвелла": "F B L R F B L R L R",
 "Крест Кристмана": "R' M2 S2 U2 M2 S2 D2 R",
 "Шахматный кубик 3-го порядка": "z' U2 M2 U M2 U2 S2 D' S2 z U2 M2 U M2 U2 S2 D' S2 M' S' M S",
 "Шахматный кубик 6-го порядка": "z' U2 M2 U M2 U2 S2 D' S2 z U2 M2 U M2 U2 S2 D' S2 M' S' M S z' y' M2 E2 S2",
 "6Н": "D2 M' S2 M U2 y2",
 "6 минусов": "R2 F2 M2 B2 L2 M' x",
 "Два перевёрнутых диагонально-угловых столбика": "F L D2 R' D L2 D' R D2 L' F L2 F2",
 "Два угловых столбика на одной стороне (Столбики)": "R2 F D R2 D' R B2 R' D R2 D' F' R2 B2",
 "Столбики с крестом": "R2 F D R2 D' R B2 R' D R2 D' F' R2 B2 y2 R2 F D R2 D' R B2 R' D R2 D' F' R2 B2",
 "Столбики с шахматным крестом": "R2 F D R2 D' R B2 R' D R2 D' F' R2 B2 y2 R2 F D R2 D' R B2 R' D R2 D' F' L2 F2",
 "Столбики с крышей": "R2 F D R2 D' R B2 R' D R2 D' F' R2 B2 y2 R2 F D R2 D' R B2 R' D R2 D' F' L2 F2 M2 S2",
 "Четыре П": "M2 D' M2 D2 M2 U' S2 E y'",
 "Четыре Т": "M2 D' M2 D2 M2 U' S2 E y' U2",
 "4 двойных Г и 2 двойных L": "L' R' U D L R U' D' F' B' U D",
 "6 букв Т (Буквы второго порядка, вариант 1)": "U2 R2 F2 D' U B2 L2 D' U'",
 "6 букв Ф (Буквы второго порядка, вариант 1) (Вариант 1)": "U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U'",
 "6 букв Н (Буквы второго порядка, вариант 1)": "U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U'",
 "6 букв Ф (Буквы второго порядка, вариант 1) (Вариант 2)": "U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U'",
 "4 буквы Т и 2 буквы С (Буквы второго порядка, вариант 1)": "U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U'",
 "Буквы второго порядка, вариант 1, полный цикл": "U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U' U2 R2 F2 D' U B2 L2 D' U'",
 "6 Т (Буквы второго порядка, вариант 2)": "B2 D2 L R' D2 B2 L R'",
 "6 Ф (Буквы второго порядка, вариант 2) (Вариант 1)": "B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R'",
 "6 Н (Буквы второго порядка, вариант 2)": "B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R'",
 "6 Ф (Буквы второго порядка, вариант 2) (Вариант 2)": "B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R'",
 "4 Т и 2 С (Буквы второго порядка, вариант 2)": "B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R'",
 "Буквы второго порядка, вариант 2, полный цикл": "B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R' B2 D2 L R' D2 B2 L R'",
 "БДТ (Большой диагональный треугольник)": "R U F' D2 F U' F' D2 F R'",
 "БДТ (Большой диагональный треугольник) (Пасьянс 1)": "R' U B2 U' F' U B2 U' F R",
 "ББТ (Большой бортовой треугольник) (Пасьянс 2)": "F' E' R U2 R' E R U2 R' F",
 "ББТ (Большой бортовой треугольник) (Пасьянс 3)": "R E F' U2 F E' F' U2 F R'",
 "МБТ (Малый бортовой треугольник) (Пасьянс 4)": "R' D U2 B E B2 E' B D' U2 R",
 "МБТ (Малый бортовой треугольник) (Вариант 1)": "R' U2 D B' E B2 E' B' U2 D' R",
 "МБТ (Малый бортовой треугольник) (Вариант 2)": "R' D U2 B' E B2 E' B' D' U2 R",
 "Мезон (кварк – антикварк) (Вариант 1)": "U' B2 U L' F2 L U' B2 U L' F2 L",
 "Мезон (кварк – антикварк) (Вариант 2)": "L' F2 L U' B2 U L' F2 L U' B2 U",
 "Мезон (кварк – антикварк) (Вариант 3)": "R' D2 R B' U2 B R' D2 R B' U2 B",
 "Мезон (кварк – антикварк) (Вариант 4)": "D' R2 D F' L2 F D' R2 D F' L2 F",
 "Гигантский мезон (Вариант 1)": "F' U' B U2 B' U R U2 R' F B D F' D2 F D' L' D2 L B'",
 "Гигантский мезон (Вариант 2)": "B L' D2 L D F' D2 F D' B' F' R U2 R' U' B U2 B' U F",
 "Гигантский мезон (Вариант 3)": "L' B D2 B' D' R D2 R' D L R F' U2 F U L' U2 L U' R'",
 "Гигантский мезон (Вариант 4)": "R U L' U2 L U' F' U2 F R' L' D' R D2 R' D B D2 B' L",
 "Гигантский мезон (Вариант 5)": "U L2 D R B' R B' R B' D' L2 U R2 F2 U2",
 "Гигантский мезон (Куб в кубе)": "U2 F2 R2 U' L2 D B R' B R' B R' D' L2 U'",
 "Гигантский мезон с вишнями (Кубик в кубе, который опять-таки в кубе) (Вариант 1)": "R U' L F U' R2 U2 R U R' U2 D' L D F2 L2 U",
 "Гигантский мезон с вишнями (Кубик в кубе, который опять-таки в кубе. Кольца)": "U' L2 F2 D' L' D U2 R U' R' U2 R2 U F' L' U R'",
 "Гигантский мезон с вишнями (Кубик в кубе, который опять-таки в кубе) (Вариант 2)": "F' U' B U2 B' U R U2 R' F B D F' D2 F D' L' D2 L B' L' F2 L U' B2 U L' F2 L U' B2 U",
 "Гигантский мезон с вишнями (Кубик в кубе, который опять-таки в кубе) (Вариант 3)": "B L' D2 L D F' D2 F D' B' F' R U2 R' U' B U2 B' U F U' B2 U L' F2 L U' B2 U L' F2 L",
 "Кольца третьего порядка (Вариант 1)": "F' U' B U2 B' U R U2 R' F B D F' D2 F D' L' D2 L B' U' B2 U L' F2 L U' B2 U L' F2 L",
 "Кольца третьего порядка (Вариант 2)": "F2 D' R2 D' L' U' L' R B D' U B L F2 L U2",
 "Кольца третьего порядка (Вариант 3)": "R' D U2 B E B2 E' B D' U2 R y2 x R' U2 D B' E B2 E' B' U2 D' R y2 x S' M' S M y z",
 "Кольца третьего порядка (Вариант 4)": "R' D U2 B E B2 E' B D' U2 R y2 x R' D U2 B' E B2 E' B' D' U2 R y2 x S' M' S M y z",
 "Кольца третьего порядка (Вариант 5)": "R' D U2 B E B2 E' B D' U2 R L U' D2 F' E F2 E' F' U D2 L' S' M' S M y z",
 "Потусторонние кольца (Кольца второго порядка) (Вариант 1)": "R' F2 U2 R2 B' L2 D' B2 R' B2 L2 B R2 U' R2",
 "Потусторонние кольца (Кольца второго порядка) (Вариант 2)": "L' F2 D2 L2 B' R2 U' B2 L' B2 R2 B L2 D' L2",
 "Потусторонние кольца (Кольца второго порядка) (Вариант 3)": "z2 L' F2 D2 L2 B' R2 U' B2 L' B2 R2 B L2 D' L2 z2",
 "Потусторонние кольца (Кольца второго порядка) (Вариант 4)": "R F B' D' F2 D B F' R' F2 U R2 U' D R2 F B U2 B' F' R2 D'",
 "Змея": "R F B' D' F2 D B F' R' F2 U R2 U' D F2 D'",
 "Потусторонние кольца с мезоном (Вариант 1)": "R' F2 U2 R2 B' L2 D' B2 R' B2 L2 B R2 U' R2 L' F2 L U' B2 U L' F2 L U' B2 U",
 "Потусторонние кольца с мезоном (Вариант 1)": "R' S2 D2 S2 R L2 B D' B D B2 D B2 L' D L'",
 "Червяк (Змейка)": "U B2 L D B' F L' D U' L' R F' D2 R'",
 "6 флагов Г. Галла": "U' B2 L2 U M2 U' R2 F2 D F B R E R' B' R' E R2 E' R' F' B2 R2 B2 F2 S z y",
 "Рыбки": "U F2 U' B' U2 B U' F2 U' R' U2 B' U2 B R",
 "Уголки второго порядка (потусторонние уголки)": "F2 R2 D R2 D U F2 D' R' D' F L2 F' D R U'",
 "Уголки третьего порядка": "U L2 D F D' B' U L' B2 U2 F U' F' U2 B' U'",
 "Вишни второго прядка (Потусторонние вишни)": "F' D L2 U' R B L2 F' D F U' F' L' B D L F'",
 "Вишни третьего порядка": "D F2 U' B F' L R' D L2 U' B R2 B' U L2 U'",
 "Эшер (Пропеллер)": "U F2 D2 R2 U' L B2 R F D F R F' D' L2 U2",
 "Винт (Тройные крюки. Сюрикен)": "U' L2 U2 R2 U' B2 L' B D R' B' L' B' D2 B' L D B' U'",
 "Ракета второго порядка": "D U L2 B2 D U' F' U F' R F2 R' F D' B2 L2 D' U'",
 "Ракета третьего порядка": "B2 U L2 R2 D' F' D' R U F2 L2 U L' D2 L R B' U",
 "Трехцветная диагональ": "D2 U B2 U2 B2 L2 B2 D F' L' U' F2 D2 F D B' L F U'",
 "Реверс (Вариант 1)": "U R U2 R F2 L U2 R F' B' R2 D R' L U2 F2 D2 F R2 D",
 "Реверс (Вариант 2)": "F B R2 U R' L U2 F2 D2 B R2 U' D' R F2 L U2 R F2 R",
 "Реверс (Вариант 3)": "R L F U2 R2 U' D' F2 R' F B U L2 B2 D2 R2 D' L2 D B2 D",
 "Реверс (Вариант 4)": "U D R F B' U2 R2 U R L' F L2 U2 B2 L2 F L2 F' R2 L2 F L2",
 "6 букв П ножками наружу (Вариант 1)": "R E F' U2 F E' F' U2 F R' E S E' S'",
 "6 букв П ножками наружу (Вариант 2)": "R F' U2 F E F' U2 F E' R' S E S' E'",
 "6 букв П ножками наружу (Вариант 3)": "F' E' R U2 R' E R U2 R' F S E S' E'",
 "6 букв П ножками наружу (Вариант 4)": "F' R U2 R' E' R U2 R' E F E S E' S'",
 "6 букв П ножками наружу (Вариант 5)": "L' R' R' F' L' B' U B L F R U' R L R L' F B' U D' R L'",
 "6 букв П ножками наружу (Вариант 6)": "L' R' R' F' L' B' U B L F R U' R L M E' M' E",
 "6 букв П ножками наружу (Вариант 7)": "L' R' U R' F' L' B' U' B L F R R L E' M E M'",
 "6 букв П ножками наружу (Вариант 8)": "B F F R B L U' L' B' R' F' U F' B' E' M E M'",
 "6 букв П ножками наружу (Вариант 9)": "B F U' F R B L U L' B' R' F' F' B' M E' M' E",
 "6 букв П ножками наружу (Вариант 10)": "y D S' U' B' D M' D' B E",
 "6 букв П ножками наружу (Вариант 11)": "E' B' D M D' B U S D' y'",
 "6 букв П ножками наружу (Вариант 12)": "y' D' M' U L D' S' D L' E'",
 "6 букв П ножками наружу (Вариант 13)": "E L D' S D L' U' M D y",
 "6 букв П ножками наружу (Вариант 14)": "E L D' F' B R D' L' E R z y",
 "6 букв П ножками наружу (Вариант 15)": "D' U B D' L' R F D' B' D' U L",
 "6 Букв П ножками внутрь (Вариант 16)": "U R2 B M' B' L' R' B' D' F' M F U",
 "6 Букв П ножками внутрь (Вариант 17)": "U' F' M' F D B R L B M B' R2 U'",

 # https://zakubi.com/blog/statja/uzory-na-kubike-rubika.html
 "Замена центров": "E M E' M'",
 "Шахматы (Шахматы с точками)": "M2 S2 E2",
 "Шахматы (Вариант 2)": "R2 L2 F2 B2 U2 D2",
 "Кресты со всех сторон": "L2 R' B2 F2 D2 B2 F2 L2 R2 U2 R'",
 "Буквы П со всех сторон": "R U R' U' y R U R' U' y R U R' U' y R U R' U' y R U R' U' y R U R' U' y R U R' U' y ",

 # https://speedcubing.ru/tutorial/3x3x3/patterns
 "Шахматы с точками": "M2 E2 S2 S' M' S M",
 "4 буквы П": "M2 D' M2 D2 M2 U' S2 E",
 "6 флагов": "U' B2 L2 U M2 U' R2 F2 D F B R E R' B' R' E R2 E' R' F' B2 R2 B2 F2 S",
}


def Count():
 return len(Patterns)


def Get(ID):
 Result = Patterns.get(ID, None)
 return Result.split(" ") if Result else []


def GetPattern(ID):
 return Patterns.get(ID, "")


def Names():
 return Patterns.keys()
